import type { IProduct } from "./interface";

export const products: IProduct[] = [
  {
    id: "001",
    title: "Sony WH-1000XM5 Wireless Headphones",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.8,
    price: 349,
  },
  {
    id: "002",
    title: "Apple MacBook Pro 14-inch M2",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.9,
    price: 1999,
  },
  {
    id: "003",
    title: "Samsung Galaxy S24 Ultra",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.7,
    price: 1299,
  },
  {
    id: "004",
    title: "Logitech MX Master 3S Wireless Mouse",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.6,
    price: 99,
  },
  {
    id: "005",
    title: "Dell Ultrasharp 27-inch 4K Monitor",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.5,
    price: 699,
  },
  {
    id: "006",
    title: "Anker PowerCore 20,000mAh Portable Charger",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.4,
    price: 59,
  },
  {
    id: "007",
    title: "Canon EOS R50 Mirrorless Camera",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.7,
    price: 899,
  },
  {
    id: "008",
    title: "Google Nest Learning Thermostat",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.3,
    price: 249,
  },
  {
    id: "009",
    title: "Amazon Echo Studio Smart Speaker",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.5,
    price: 199,
  },
  {
    id: "010",
    title: "Asus ROG Zephyrus G14 Gaming Laptop",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.8,
    price: 1699,
  },
  {
    id: "011",
    title: "Fitbit Charge 6 Fitness Tracker",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.2,
    price: 129,
  },
  {
    id: "012",
    title: "DJI Mini 4K Drone Camera",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.6,
    price: 599,
  },
  {
    id: "013",
    title: "TP-Link WiFi 6 Router AX1800",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.4,
    price: 89,
  },
  {
    id: "014",
    title: "Kindle Paperwhite (11th Gen)",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.5,
    price: 149,
  },
  {
    id: "015",
    title: "Samsung 1TB Portable SSD T7",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.7,
    price: 139,
  },
  {
    id: "016",
    title: "Bose SoundLink Flex Bluetooth Speaker",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.6,
    price: 149,
  },
  {
    id: "017",
    title: "Razer BlackWidow V4 Pro Mechanical Keyboard",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.7,
    price: 229,
  },
  {
    id: "018",
    title: "GoPro HERO12 Action Camera",
    image: "https://inspiretemplates.com/E-shope/image/cache/catalog/product/28-212x212.jpg",
    rating: 4.8,
    price: 399,
  },
];
